import type { Env, User, Member, RouteTemplate, ClimbPlan, ClimbRecord, RecordImage } from './types';import { html } from './lib/html';import { hashPassword, verifyPassword, randomId } from './lib/crypto';import { getJson, putJson, listJson, del } from './lib/kv';import { currentUser, createSession, cookie, clearCookie, sid } from './lib/session';import { validUser, validPass, json, ok, err } from './lib/validation';import { dashboard, aa } from './lib/stats';import * as ex from './lib/export';
export default {async fetch(req:Request,env:Env){try{return await handle(req,env)}catch(e:any){return err(e.message||'服务器错误',500)}}};
function id(){return randomId(12)}function now(){return new Date().toISOString()}function canWrite(u:User,o:any){return u.role==='Owner'||!o?.createdBy||o.createdBy===u.username}function page<T>(a:T[],url:URL){const p=Number(url.searchParams.get('page')||1),n=Number(url.searchParams.get('pageSize')||50);return a.slice((p-1)*n,p*n)}
async function handle(req:Request,env:Env){const url=new URL(req.url),p=url.pathname;if(!p.startsWith('/api'))return new Response(html,{headers:{'content-type':'text/html;charset=utf-8'}});if(p==='/api/init-owner'&&req.method==='POST'){const b=await json(req);if(!validUser(b.username)||!validPass(b.password))return err('账号或密码不符合规则');const users=await env.CLIMB_KV.list({prefix:'users:',limit:1});if(users.keys.length)return err('Owner 已初始化',409);const u:User={username:b.username,role:'Owner',passwordHash:await hashPassword(b.password),createdAt:now()};await putJson(env.CLIMB_KV,`users:${u.username}`,u);return ok({username:u.username,role:u.role})}
if(p==='/api/login'&&req.method==='POST'){const b=await json(req);const u=validUser(b.username)?await getJson<User>(env.CLIMB_KV,`users:${b.username}`):null;if(!u||!await verifyPassword(String(b.password||''),u.passwordHash))return err('账号或密码错误',401);const s=await createSession(env,u.username);return ok({username:u.username,role:u.role},{headers:{'Set-Cookie':cookie(s)}})}
if(p==='/api/logout'&&req.method==='POST'){const s=sid(req);if(s)await del(env.CLIMB_KV,`sessions:${s}`);return ok(null,{headers:{'Set-Cookie':clearCookie()}})}const u=await currentUser(req,env);if(!u)return err('未登录',401);if(p==='/api/me')return ok({username:u.username,role:u.role});
if(p.match(/^\/api\/members\/[^/]+$/)&&req.method==='GET'){const mid=p.split('/').pop()!,member=await getJson<Member>(env.CLIMB_KV,`members:${mid}`),records=(await listJson<ClimbRecord>(env.CLIMB_KV,'records:')).filter(r=>r.memberIds.includes(mid));return ok({member,records,stats:memberStats(records)})}
let m=p.match(/^\/api\/(members|templates|plans|records)(?:\/([^/]+))?$/);if(m)return crud(req,env,u,m[1],m[2],url);
if(p.startsWith('/api/dashboard')){const records=await listJson<ClimbRecord>(env.CLIMB_KV,'records:'),members=await listJson<Member>(env.CLIMB_KV,'members:');return ok(dashboard(records,members))}
if(p.startsWith('/api/records/from-plan/')&&req.method==='POST'){const pid=p.split('/').pop()!,pl=await getJson<ClimbPlan>(env.CLIMB_KV,`plans:${pid}`);if(!pl)return err('计划不存在',404);const r:ClimbRecord={id:id(),planId:pl.id,routeName:pl.routeName,difficulty:pl.difficulty,date:pl.planDate,memberIds:pl.memberIds,plannedDistanceKm:pl.plannedDistanceKm,plannedDurationMin:pl.plannedDurationMin,plannedElevationM:pl.plannedElevationM,actualDistanceKm:pl.plannedDistanceKm,actualDurationMin:pl.plannedDurationMin,actualElevationM:pl.plannedElevationM,budget:pl.budget,expenses:[],bodyData:[],roadNotes:'',riskNotes:'',weather:'',review:'',otherNotes:'',createdBy:u.username,createdAt:now(),updatedAt:now()};await putJson(env.CLIMB_KV,`records:${r.id}`,r);return ok(r)}
if(p.match(/^\/api\/members\/[^/]+\/stats$/)){const mid=p.split('/')[3],records=(await listJson<ClimbRecord>(env.CLIMB_KV,'records:')).filter(r=>r.memberIds.includes(mid));return ok(memberStats(records))}
if(p.match(/^\/api\/records\/[^/]+\/aa$/)){const r=await getJson<ClimbRecord>(env.CLIMB_KV,`records:${p.split('/')[3]}`);return r?ok(aa(r)):err('记录不存在',404)}
if(p.match(/^\/api\/records\/[^/]+\/images/))return images(req,env,u,p,url);
if(p.startsWith('/api/export/'))return exportData(env,p,url);return err('Not Found',404)}
async function crud(req:Request,env:Env,u:User,type:string,item?:string,url?:URL){const map:any={members:'members',templates:'routeTemplates',plans:'plans',records:'records'},prefix=map[type]+':';if(req.method==='GET'&&!item)return ok(page(await listJson<any>(env.CLIMB_KV,prefix),url!));if(req.method==='GET'&&item)return ok(await getJson(env.CLIMB_KV,prefix+item));if(req.method==='DELETE'&&item){const old=await getJson<any>(env.CLIMB_KV,prefix+item);if(!canWrite(u,old))return err('无权限',403);await del(env.CLIMB_KV,prefix+item);return ok() }const b=await json(req);if(req.method==='POST'){b.id=id();b.createdBy=u.username;b.createdAt=now();b.updatedAt=now();await putJson(env.CLIMB_KV,prefix+b.id,b);return ok(b)}if(req.method==='PUT'&&item){const old=await getJson<any>(env.CLIMB_KV,prefix+item);if(!canWrite(u,old))return err('无权限',403);b.id=item;b.createdBy=old?.createdBy||u.username;b.createdAt=old?.createdAt||now();b.updatedAt=now();await putJson(env.CLIMB_KV,prefix+item,b);return ok(b)}return err('方法不支持',405)}
function memberStats(rs:ClimbRecord[]){const distance=rs.reduce((a,r)=>a+r.actualDistanceKm,0),elev=rs.reduce((a,r)=>a+r.actualElevationM,0),dur=rs.reduce((a,r)=>a+r.actualDurationMin,0);return{distance,elev,duration:dur,count:rs.length,pace:distance?(dur/distance).toFixed(2):'0',speed:dur?(distance/(dur/60)).toFixed(2):'0'}}
async function images(req:Request,env:Env,u:User,p:string,url:URL){const parts=p.split('/'),rid=parts[3],img=parts[5];if(req.method==='GET'&&!img)return ok(await listJson<RecordImage>(env.CLIMB_KV,`images:${rid}:`));if(req.method==='DELETE'&&img){const meta=await getJson<RecordImage>(env.CLIMB_KV,`images:${rid}:${img}`);if(meta)await env.CLIMB_IMAGES.delete(meta.r2Key);await del(env.CLIMB_KV,`images:${rid}:${img}`);return ok()}if(req.method==='POST'){const form=await req.formData(),files=form.getAll('files') as File[],out=[];for(const f of files){const iid=id(),key=`records/${rid}/${iid}-${f.name}`,meta:RecordImage={id:iid,recordId:rid,r2Key:key,category:(form.get('category') as any)||'风景照',note:String(form.get('note')||''),fileName:f.name,contentType:f.type,size:f.size,createdAt:now()};await env.CLIMB_IMAGES.put(key,f.stream(),{httpMetadata:{contentType:f.type}});await putJson(env.CLIMB_KV,`images:${rid}:${iid}`,meta);out.push(meta)}return ok(out)}if(req.method==='GET'&&img==='download'){const metas=await listJson<RecordImage>(env.CLIMB_KV,`images:${rid}:`);return ok(metas.map(m=>({fileName:m.fileName,url:`/api/records/${rid}/images/${m.id}/file`})))}if(req.method==='GET'&&parts[6]==='file'){const meta=await getJson<RecordImage>(env.CLIMB_KV,`images:${rid}:${img}`);if(!meta)return err('图片不存在',404);const obj=await env.CLIMB_IMAGES.get(meta.r2Key);return obj?new Response(obj.body,{headers:{'content-type':meta.contentType}}):err('文件不存在',404)}return err('图片接口错误',400)}
async function exportData(env:Env,p:string,url:URL){const fmt=url.searchParams.get('format')||'json';let rows:any[]=p.includes('/record/')?[await getJson(env.CLIMB_KV,`records:${p.split('/').pop()}`)]:await listJson(env.CLIMB_KV,'records:');rows=rows.filter(Boolean);let body='',ct='text/plain';if(fmt==='csv')body=ex.csv(rows);else if(fmt==='jsonc')body=ex.jsonc(rows);else if(fmt==='jsonl')body=ex.jsonl(rows);else if(fmt==='mysql'||fmt==='mariadb')body=ex.sql(rows);else if(fmt==='xlsx'){body=ex.xlsxHtml(rows);ct='application/vnd.ms-excel'}else{body=JSON.stringify(rows,null,2);ct='application/json'}return new Response(body,{headers:{'content-type':ct+';charset=utf-8','content-disposition':`attachment; filename="friends-climbing.${fmt}"`}})}
